# Generated by Django 5.1.3 on 2025-01-19 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vente',
            new_name='Sale',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='purchase_date',
            new_name='sale_date',
        ),
    ]
