# Generated by Django 5.1.3 on 2025-02-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0002_rename_vente_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='products',
            new_name='product',
        ),
    ]
