# Generated by Django 5.1.3 on 2025-02-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0003_rename_products_sale_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='products',
            new_name='product',
        ),
    ]
