# Generated by Django 5.1.3 on 2025-02-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0005_alter_bill_total_amount_alter_sale_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='customer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.CharField(max_length=100),
        ),
    ]
